### ISSUE TITLE
Not working in Sketch 3.8.3

### ISSUE THREAD

**Issue by PGRdesign** [sketchplugins/plugin-requests#11]
I was willing to use this plugin since is the only one I can find to replace a font from all layers in an artboard, but once downloaded, I selected the artboard, hit "Replace Font" within the plugins menu, and it did like a flash (like a fast blink) but nothing didn't happened.

At that point, the pop-up should have come up I think, but it doesn't trigger it well.

Let me know if you need more details!

**Comment by sogen** [comment]
Just installed it and It's working here (Yosemite)
installed it via double clicking the .sketchplugin file

**Comment by bomberstudios** [comment]
Ditto here, working fine…

**Comment by PGRdesign** [comment]
Tried installing the plugin by double clicking instead of copying to the plugins folder and still doesn't works on my side. Using Sketch app 3.8.3 under OSX El Capitan (10.11.5).

The same behavior, I open the sketch file, go to the plugins menu, click on "Replace Font", a small blink but nothing else happens. Tried with different sketch files (more and less artboards/layers) but still always getting the same issue.

Could it be related with my other plugins? could another plugin create conflict?

**Comment by bomberstudios** [comment]
Can you take a look at Console.app and see if there's anything there?

**Comment by PGRdesign** [comment]
<img width="712" alt="captura de pantalla 2016-06-02 a las 11 17 59" src="https://cloud.githubusercontent.com/assets/14013660/15740110/b61c33ea-28b3-11e6-98f3-675a5aee63f3.png">

@bomberstudios  this is what I see after clicking the plugin in the console.

**Comment by bomberstudios** [comment]
Ah, you have saved *the whole HTML page for the plugin*…

Get this instead: https://raw.githubusercontent.com/sketchplugins/plugin-requests/master/Replace%20Font.sketchplugin (you get there by clicking the 'Raw' button in the page.

**Comment by PGRdesign** [comment]
Oh! thanks a lot!! 👍 

Cheers!
