### ISSUE TITLE
Sketch Library/Document Theme Swap

### ISSUE THREAD

**Issue by mcbridek** [sketchplugins/plugin-requests#14]
I've thinking about the possibility of a plugin that can swap out styles, colours, font's, symbols and assets on a single click. The idea here is to have a design system (Sketch Library) with 3/4 theme's that can be swapped out at any time on a single click. The best way I can explain this is by showing an example from semantic ui.

Check out the Video: https://streamable.com/npdj8

**Comment by bomberstudios** [comment]
That's an interesting idea, will forward it to the sketchplugins.com forum : )

**Comment by SaulGarza** [comment]
I love this idea, it would help me so much with the current sketch project im working on actually, ill explore this a bit and see what i can do.

**Comment by Pausansol** [comment]
Maybe this will work for you, take a look: https://github.com/Pausansol/Camilo
