### ISSUE TITLE
A sidebar to display my library and pick and use icons from

### ISSUE THREAD

**Issue by JonasASchmidt** [sketchplugins/plugin-requests#20]
I'm working with an extensive product design library, where the UI is builtg as components using nested smybols and a "folder" structure by symbol naming. I find the standard multilevel dropdown if sketch hard to use to find the icons I need quickly and put them on the stage. I would love a full height sidebar I can open (that stays open on demand) and close, where my symbols are neatly grouped and accessible as list/grid items with thumbnail previews to drag and drop them onto the stage for example. Somewhat like a simplified pallette from Creative Cloud apps. That shouldn't be too hard, right? As i'm a UX designer I could provide concept and sketches. I also would try to develop it myself, with some help of a developer. Drop me a line if you're intereted in cooperating.

**Comment by robintindale** [comment]
Until someone makes a more visual panel, Sketch Runner may help you. I know it's not the same, but it could be part of the way there. You can use it to search across all your libraries

![](https://i.imgur.com/l8Kfxhi.gif)

**Comment by avkvirtru** [comment]
@JonasASchmidt did you find anything else for this besides Sketch Runner? I find myself wishing for this on a regular basis.

**Comment by timothymills** [comment]
It’s not a sidebar, but Symbol Browser might be close to what you’re looking for. http://symbol-browser.pratikshah.website/

**Comment by JonasASchmidt** [comment]
Thanks for the input. For the time being I'm working with Sketch Runner Pro.
