### ISSUE TITLE
do_objectID / layer.id not unique

### ISSUE THREAD

**Issue by adontz** [sketchplugins/plugin-requests#26]
Hello,

I'm writing a plug-in for my coworker designer and I have faced very strange problem. While do_objectID (as parsed from file) or layer.id (as read by plugin or script) look like UUID, they repeat. Not only between files, but also within file. Can you clarify if this is a bug and what are minimum uniqueness guarantee for layer.id? Global (obviously broken), within document (obviously broken), within artboard, within parent layer?

**Comment by bomberstudios** [comment]
Hi @adontz, could you please send an email with a sample file to developer@sketch.com so we can take a look? Thanks!

**Comment by adontz** [comment]
@bomberstudios Can you kindly answer my original question?
