### ISSUE TITLE
Hiding certain layers in a document

### ISSUE THREAD

**Issue by james595832** [sketchplugins/plugin-requests#28]
I am creating a page layout design and in between all the components I have little spacer icons. This is useful for devs but when presenting the screens to product owners etc they distract from the design. I know an option is to group all those spacer layers and turn them on and off but I wanted to see if anyone has / knows of a plugin to do the job. I know I can do this but when we have multiple people working on files with different sketch knowledge a simple override option built into the component would make this super easy.

Think it could be a useful plugin. If you could assign your components a variable and then in the overrides this allows you to turn off any component with that variable name.

**Comment by bomberstudios** [comment]
Answered in https://sketchplugins.com/d/1732-hiding-certain-layers-in-a-document so closing this one : )
