### ISSUE TITLE
Replace Font.sketchplugin error

### ISSUE THREAD

**Issue by chris-dura** [sketchplugins/plugin-requests#4]
Hello!

New to Sketch... when trying to run the `Replace Font.sketchplugin` I get the following error:

```
ReferenceError: Can't find variable: doc
stack: onRun@/Users/CDura/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin:5:20
line: 5
sourceURL: /Users/CDura/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin


Script executed in 0.007434s
```

Sketch Version 3.3.2 (12043)

**Comment by bomberstudios** [comment]
How have you installed it?

**Comment by chris-dura** [comment]
Sorry, I haven't really done any 101 tuts or anything, but it seemed like I didn't have to "install" it. I was just trying to figure it out without reading the manual. I just went to `Plugins > Custom Plugin...` then copy+pasted the code and hit `Run`.

**Comment by bomberstudios** [comment]
Yeah, that's what I thought.

If you download and install it by double clicking the `.sketchplugin` file, it'll work fine. However, since GitHub's UI is a disaster for single-file downloading, I'll try to update the plugin so that it works when copying & pasting to Sketch 3.3

**Comment by chris-dura** [comment]
Cool, thanks!
