### ISSUE TITLE
压缩图片

### ISSUE THREAD

**Issue by allurewu** [sketchplugins/plugin-requests#47]
能否开发压缩图片的插件，现在好的插件不能用了

**Comment by allurewu** [comment]
现在我的工作流程是：导出图片-找到压缩软件或浏览器-拖入图片-压缩下载，这实在太麻烦了。如果有sketch插件的话，我在sketch导出图片的时候就可以压缩就完美了

**Comment by bomberstudios** [comment]
Take a look at https://imageoptim.com/sketch
